first = input('What is your first name?')
last = input('What is your last name?')
print(f"Your name is {last}, {first} {last}") 
print("Your name is" + last + ',' + first)
output = "Hello {} {} ".format(first,last)
print(output)